"""RPC constants for kvdb."""
SET = "SET"
GET = "GET"
DELETE = "DELETE"
OK = "100:OK"
UNKNOWN_ERROR = "000:UnknownError"
INVALID_COMMAND = "401:Invalid Command"
INVALID_KEY = "402:Invalid_Key"
KEY_NOT_FOUND = "403:Key_Not_Found"
TIMEOUT_ERROR = "405:TimeoutError"
